services:
    captcha:
        container_name: captcha

        # run docker script from subdirectory
        build:
            context: ./captcha
            dockerfile: Dockerfile

        # mount volume
        volumes:
            - type: bind
              source: ./captcha
              target: /workspace/captcha
        working_dir: /workspace/captcha

        # map ports to host
        ports:
            - "8080:8080"

    attack:
        container_name: attack

        build:
            context: ./attack
            dockerfile: Dockerfile
        
        volumes:
            - type: bind
              source: ./attack
              target: /workspace/attack
        working_dir: /workspace/attack

        # config for pytorch IPC
        # see: https://docs.docker.com/compose/gpu-support/
        # see: https://github.com/NVIDIA/nvidia-container-toolkit?tab=readme-ov-file
        stdin_open: true
        tty: true
        ipc: host

        ports:
            - '8888:8888'
