services:
    # captcha:
    #     container_name: captcha

    #     build:
    #         context: ./captcha
    #         dockerfile: Dockerfile

    #     volumes:
    #         - type: bind
    #           source: ./captcha
    #           target: /workspace/captcha
    #     working_dir: /workspace/captcha

    #     ports:
    #         - "8080:8080"
    
    attack:
        container_name: attack

        build:
            context: ./attack
            dockerfile: Dockerfile

        # depends_on:
        #     captcha:
        #         condition: service_started
        
        volumes:
            - type: bind
              source: ./attack
              target: /workspace/attack
        working_dir: /workspace/attack

        # config for pytorch IPC
        # see: https://docs.docker.com/compose/gpu-support/
        # see: https://github.com/NVIDIA/nvidia-container-toolkit?tab=readme-ov-file
        # stdin_open: true
        # tty: true
        # ipc: host
        # environment:
        #     - NVIDIA_VISIBLE_DEVICES=all
        #     - NVIDIA_DRIVER_CAPABILITIES=compute,utility
